### ISSUE TITLE
[FEATURE REQUEST]: Module to support Azure AD/Entra

### ISSUE THREAD

**Issue by mattboyd-aws** [aws-samples/toolkit-for-aws-transfer-family#28]
**Is your feature request related to a problem? Please describe.**
I need to support authentication to Azure AD/Entra for authentication. Currently, there is no IdP module in the solution for this.

**Describe the solution you'd like**
An IdP module that supports integrating user authentication for Azure AD/Entra

**Describe alternatives you've considered**
Using AD/LDAP - but this is not feasible for many customers.

**Additional context**

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by allynaws** [comment]
Matt, IHAC that would require Azure authentication to use Toolkit. They do like many of the current features of Toolkit. I can share customer name with you direct. allynaws

**Comment by mattboyd-aws** [comment]
Looking into this now.
